version: "3"
services:
  node-app:
    container_name: app-exp
    volumes:
      - /home/sayed/node-app:/app:ro
    ports:
      - 4000:4000
    depends_on:
      -  mongo


  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  redis:
    image: redis


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo 



  nginx:
    image: nginx
    volumes:
      - ./nginx/defaulte.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "80:80"
    depends_on:
      - node-app








volumes:
  mongo-db:

