FROM node:slim
WORKDIR /app
COPY package.json .
RUN npm install
ARG NODE_ENV
RUN if ["${NODE_ENV}" = "prodaction" ] ; \
    then npm install --only=prodaction; \
    else npm install ; \
    fi
COPY . .
EXPOSE 4000
CMD [ "npm" ,"run", "start-dev"]
